apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: app
data:
  index.html: |
    <html>
      <head>
        <title>Nginx Project</title>
      </head>
      <body>
        <h1>This is Deployment One</h1>
      </body>
    </html>